### ISSUE TITLE
Yami Landing Page

### ISSUE THREAD

**Issue by Xevoxe** [Xevoxe/Yami#7]
## Description
As a **site visitor** 
I want **navigate to the Yami Landing Page** 
So I can **learn more about the project.**

## Initiative / goal
The Yami Landing Page will be the entry point to learning about the project.  As so it will be the first impression that visitors will have.

### Hypothesis
Increased web traffic and more attention on the project will be key indicators of the success of this epic.

## Acceptance criteria and must have scope
- [x] Header/Navigation
- [x] Hero Slider
- [x] Audio Media Player
- [x] Game Content Section
- [x] Dev Log Aside
- [x] Footer
Define what is a must-have for launch and in-scope. Keep this section fluid and dynamic until you lock-in priority during planning.

## Stakeholders
Jin Co-Lead
Yami Team

## Timeline
**Soft Deadline August 31, 2019**
- Dev Log Epic Development
- Vacation 8th-18th
- WGU Class
